#!/bin/sh
#
# An example hook script to check the commit log message.
# Called by "git commit" with one argument, the name of the file
# that has the commit message.  The hook should exit with non-zero
# status after issuing an appropriate message if it wants to stop the
# commit.  The hook is allowed to edit the commit message file.
#
# To enable this hook, rename this file to "commit-msg".

# Uncomment the below to add a Signed-off-by line to the message.
# Doing this in a hook is a bad idea in general, but the prepare-commit-msg
# hook is more suited to it.
#
# SOB=$(git var GIT_AUTHOR_IDENT | sed -n 's/^\(.*>\).*$/Signed-off-by: \1/p')
# grep -qs "^$SOB" "$1" || echo "$SOB" >> "$1"

# This example catches duplicate Signed-off-by lines.

# Extract the commit message from the commit message file
commit_msg_file=$1
commit_msg=$(cat $commit_msg_file)

# Ensure the commit message follows Angular commit message convention
# Example pattern for Angular convention: "<type>(<scope>): <message>"

msg_re="^(:.*:) (feat|fix|docs|style|refactor|perf|test|workflow|build|ci|chore|release|)(\(.+\))?: .{1,50}"

if [[ ! $commit_msg =~ $msg_re ]]; then
    echo $commit_msg
    echo "Invalid commit message! Please follow the Angular commit message convention:"
    echo "<type>(<scope>): <message>"
    echo "Refer to the Angular commit message guidelines for more details."
    exit 1
fi

test "" = "$(grep '^Signed-off-by: ' "$1" |
	 sort | uniq -c | sed -e '/^[ 	]*1[ 	]/d')" || {
	echo >&2 Duplicate Signed-off-by lines.
	exit 1
}
