#!/usr/bin/env pwsh
# Save-PackageVersions.ps1 - Lock Git Submodules Versions (V2 Format)
# 
# This script generates a packages-lock.el file compatible with the
# Emacs version manager (mcg-lock-packages).

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RootDir = Split-Path -Parent (Split-Path -Parent $ScriptDir)
Push-Location $RootDir

Write-Host ""
Write-Host "Locking package versions (V2 format)..." -ForegroundColor Cyan
Write-Host ""

# Output file
$outputFile = "emacs/site-lisp/packages-lock.el"

# Get current timestamp
$timestamp = Get-Date -Format "yyyy-MM-ddTHH:mm:sszzz"
$platform = if ($IsWindows -or $env:OS -eq "Windows_NT") { "windows-nt" } elseif ($IsMacOS) { "darwin" } else { "gnu/linux" }

# Generate file header
$output = @"
;;; packages-lock.el --- Locked package versions -*- lexical-binding: t; -*-

;; Filename: packages-lock.el
;; Description: Locked extension package versions
;; Auto-generated: $timestamp
;; DO NOT EDIT - This file is auto-generated by Save-PackageVersions.ps1

;;; Commentary:
;;
;; This file records all Git Submodules commit hashes.
;; Used for version control and rollback.
;;

;;; Code:

(defvar mcg-packages-lock
  '(
"@

# Get all Emacs submodules
$packages = @()
$count = 0

Get-ChildItem -Path "emacs/site-lisp/extensions" -Directory -Recurse |
    Where-Object { Test-Path "$($_.FullName)/.git" } |
    ForEach-Object {
        Push-Location $_.FullName
        
        $commit = git rev-parse HEAD 2>$null
        $branch = git symbolic-ref --short HEAD 2>$null
        
        if ($commit) {
            $relativePath = $_.FullName.Replace("$RootDir\emacs\site-lisp\extensions\", "").Replace("\", "/")
            
            # Build the entry with optional branch
            if ($branch) {
                $packages += "    (`"$relativePath`" :commit `"$commit`" :branch `"$branch`")"
            } else {
                $packages += "    (`"$relativePath`" :commit `"$commit`")"
            }
            
            $count++
            Write-Host "[OK] $relativePath" -ForegroundColor Green -NoNewline
            Write-Host " -> $($commit.Substring(0,7))" -ForegroundColor Gray -NoNewline
            if ($branch) {
                Write-Host " ($branch)" -ForegroundColor Cyan
            } else {
                Write-Host " (detached)" -ForegroundColor Yellow
            }
        }
        
        Pop-Location
    }

$output += $packages -join "`n"

# Get Emacs version if available
$emacsVersion = "unknown"
try {
    $emacsVersion = (emacs --version 2>$null | Select-Object -First 1) -replace "GNU Emacs ", ""
} catch {}

$output += @"

    )
  "Locked package versions with commit hashes and branch info")

(defvar mcg-lock-metadata
  '(:locked-at "$timestamp"
    :emacs-version "$emacsVersion"
    :platform "$platform")
  "Lock file metadata")

(provide 'mcg-packages-lock)
;;; packages-lock.el ends here
"@

# Write to file
Set-Content -Path $outputFile -Value $output -Encoding UTF8

Write-Host ""
Write-Host "[OK] Locked $count package versions" -ForegroundColor Green
Write-Host "Output: $outputFile" -ForegroundColor Cyan
Write-Host ""
Write-Host "Tip: Commit this file to Git for team consistency" -ForegroundColor Yellow
Write-Host ""

Pop-Location
