;; -*- mode: eask; lexical-binding: t -*-

(package "majutsu"
         "0.6.0"
         "Interface to jj version control system")

(website-url "https://github.com/0WD0/majutsu")
(keywords "vc" "tools")

(package-file "majutsu.el")

(script "test" "eask test ert test/*.el")

(source "gnu")

(depends-on "emacs" "29.1")
(depends-on "magit" "3.3.0")
(depends-on "transient" "0.5.0")

(source 'melpa)
(source 'jcs-elpa)

(development
 (depends-on "ellsp"))
