local M = {}

function M.get_base_specs()
  return {
    { src = "https://github.com/nvim-tree/nvim-web-devicons", name = "nvim-web-devicons" },
    { src = "https://github.com/catppuccin/nvim", name = "catppuccin" },
    { src = "https://github.com/folke/which-key.nvim", name = "which-key.nvim" },
    { src = "https://github.com/folke/tokyonight.nvim", name = "tokyonight.nvim" },
    { src = "https://github.com/rebelot/kanagawa.nvim", name = "kanagawa.nvim" },
    { src = "https://github.com/folke/snacks.nvim", name = "snacks.nvim" },
    { src = "https://github.com/folke/flash.nvim", name = "flash.nvim" },
    { src = "https://github.com/chrisgrieser/nvim-spider", name = "nvim-spider" },
    { src = "https://github.com/echasnovski/mini.nvim", name = "mini.nvim" },
    { src = "https://github.com/folke/noice.nvim", name = "noice.nvim" },
    { src = "https://github.com/akinsho/bufferline.nvim", name = "bufferline.nvim" },
    { src = "https://github.com/lewis6991/gitsigns.nvim", name = "gitsigns.nvim" },
    { src = "https://github.com/folke/trouble.nvim", name = "trouble.nvim" },
    { src = "https://github.com/folke/todo-comments.nvim", name = "todo-comments.nvim" },
    { src = "https://github.com/saghen/blink.lib", name = "blink.lib" },
    { src = "https://github.com/saghen/blink.cmp", name = "blink.cmp" },
    { src = "https://github.com/rafamadriz/friendly-snippets", name = "friendly-snippets" },
    { src = "https://github.com/nvim-treesitter/nvim-treesitter", name = "nvim-treesitter" },
    { src = "https://github.com/nvim-treesitter/nvim-treesitter-context", name = "nvim-treesitter-context" },
    { src = "https://github.com/stevearc/conform.nvim", name = "conform.nvim" },
    { src = "https://github.com/williamboman/mason.nvim", name = "mason.nvim" },
    { src = "https://github.com/williamboman/mason-lspconfig.nvim", name = "mason-lspconfig.nvim" },
    { src = "https://github.com/WhoIsSethDaniel/mason-tool-installer.nvim", name = "mason-tool-installer.nvim" },
    { src = "https://github.com/jay-babu/mason-nvim-dap.nvim", name = "mason-nvim-dap.nvim" },
    { src = "https://github.com/neovim/nvim-lspconfig", name = "nvim-lspconfig" },
    { src = "https://github.com/mfussenegger/nvim-dap", name = "nvim-dap" },
    { src = "https://github.com/rcarriga/nvim-dap-ui", name = "nvim-dap-ui" },
    { src = "https://github.com/theHamsta/nvim-dap-virtual-text", name = "nvim-dap-virtual-text" },
    { src = "https://github.com/nvim-neotest/nvim-nio", name = "nvim-nio" },
    { src = "https://github.com/b0o/SchemaStore.nvim", name = "SchemaStore.nvim" },
    { src = "https://github.com/nvim-lua/plenary.nvim", name = "plenary.nvim" },
    { src = "https://github.com/MunifTanjim/nui.nvim", name = "nui.nvim" },
    { src = "https://github.com/dhruvasagar/vim-table-mode", name = "vim-table-mode" },
    { src = "https://github.com/HakonHarnes/img-clip.nvim", name = "img-clip.nvim" },
    { src = "https://github.com/mzlogin/vim-markdown-toc", name = "vim-markdown-toc" },
    { src = "https://github.com/MeanderingProgrammer/render-markdown.nvim", name = "render-markdown.nvim" },
    { src = "https://github.com/vuki656/package-info.nvim", name = "package-info.nvim" },
    { src = "https://github.com/nvim-pack/nvim-spectre", name = "nvim-spectre" },
    { src = "https://github.com/jellydn/hurl.nvim", name = "hurl.nvim" },
    { src = "https://github.com/ray-x/guihua.lua", name = "guihua.lua" },
    { src = "https://github.com/ray-x/go.nvim", name = "go.nvim" },
    { src = "https://github.com/tpope/vim-dadbod", name = "vim-dadbod" },
    { src = "https://github.com/kristijanhusak/vim-dadbod-completion", name = "vim-dadbod-completion" },
    { src = "https://github.com/kristijanhusak/vim-dadbod-ui", name = "vim-dadbod-ui" },
    { src = "https://github.com/NvChad/nvim-colorizer.lua", name = "nvim-colorizer.lua" },
    { src = "https://github.com/windwp/nvim-ts-autotag", name = "nvim-ts-autotag" },
  }
end

return M
